[HAN-81] / [HAN-82]: Crear repositorio + Crear publicación
Hanagotchi/social pull request #1
Opened 2024-04-08 06:04 UTC by fjpacheco

2024-04-09 03:02 UTC, fjpacheco commented on docker-compose.yaml
> +      - ./app/docker/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
aqui toma el init-mongodb.js jeje

2024-04-09 03:17 UTC, fjpacheco commented
El modelo que tendrá la base de datos ya fue discutido en una reunión y está disponible en el Miro que tenemos.

Por ahora, solo se implementó el modelo de publicaciones.

2024-04-09 03:50 UTC, violetaperezandrade commented on app/controller/Social.py
> +    async def handle_create_publication(
lo llamaria post en vez de publication(aca y en todos lados, lo marco en un lugar solo para no floodear)

2024-04-09 05:11 UTC, fjpacheco commented on app/controller/Social.py
> +    async def handle_create_publication(
modificado

2024-04-09 23:48 UTC, Agustinefe requested changes

2024-04-09 23:48 UTC, Agustinefe commented on app/schemas/Post.py
> +    author_user_id: int
Ta duplicado el author id

2024-04-09 23:48 UTC, Agustinefe commented on app/schemas/Post.py
> +class PostSchema(BaseModel):
Falta la lista de fotos que pueda tener una publicacion.

2024-04-09 23:48 UTC, Agustinefe commented on app/schemas/Post.py
Se me hace raro que un post almacene el ID del usuario, y que al hacer get se devuelva eso.

Desde el front, cuando yo hago un get de una publicacion, lo ideal seria que el cliente no sea quien fetchee los datos del autor, sino que lo haga la propia API. Estos datos serian el nombre del autor, el alias, y la foto de perfil.

Otro tema: cuando el cliente solicite una lista de publicaciones, tampoco seria ideal que el cliente sea quien tenga que fetchear los datos de los autores uno por uno. Nuevamente, tarea de la api.

2024-04-11 16:58 UTC, fjpacheco commented on app/schemas/Post.py
> +class PostSchema(BaseModel):
agrega2

2024-04-11 16:59 UTC, fjpacheco commented on app/schemas/Post.py
cambia2

2024-04-11 17:03 UTC, fjpacheco commented on app/schemas/Post.py
PARA PROXIMO ENDPOINT en los gets de todos los USERS... hay que guardar en un hashset los ids de usuarios para no pedir 5 veces el mismo user de las 5 publicaciones del mismo autor. Con hashset pedimos una vez sola esa info de user y ya!
y de ahi o llamamos **paralelamente** al microserivicio de users para mapear cada id del hashmap a users.. o sino buscamos forma de enviar N ids en 1 sola query :)

2024-04-11 17:03 UTC, fjpacheco commented on app/schemas/Post.py
esto lo hablamos en su momento en la planning
solo lo remarco para recordar y no olvidar estos detalles

2024-04-11 17:38 UTC, Agustinefe commented on app/schemas/Post.py
Opino que deberiamos crear un endpoint en users que permita fetchear mas de un usuario dada una lista de ids. De esta manera es una unica query a la tabla de usuarios

2024-04-11 17:56 UTC, Agustinefe approved these changes
Gracias rey sos el mas capito 🚀

2024-04-11 19:11 UTC, merged