Han 96 - Ver perfil de un usuario X
Hanagotchi/social pull request #6
Opened 2024-04-20 03:48 UTC by feijooso

## Linked ticket in Jira
- https://hanagotchi.atlassian.net/browse/HAN-96

## Describe your changes, marking the new features and possible risks
-

## Media: upload photos or videos (if needed)
-

2024-04-20 19:44 UTC, fjpacheco requested changes

2024-04-20 19:44 UTC, fjpacheco commented on app/schemas/SocialUser.py
anda joya habria q agregar nuevo esquema (que herede de SocialUserSchema) para que retorne segun https://hanagotchi.atlassian.net/browse/HAN-96 el {name, photo, nickname} llamando user service y listop

2024-04-20 19:44 UTC, fjpacheco commented on app/main.py
> +async def get_social_user(id_user: str):
propagale para que sea de tipo int en todos lados, bah mande un str en vez int y me tiro 500

2024-04-21 00:26 UTC, feijooso commented on app/main.py
> +async def get_social_user(id_user: str):
listo

2024-04-22 00:12 UTC, feijooso commented on app/schemas/SocialUser.py
listo

2024-04-22 17:39 UTC, fjpacheco approved these changes

2024-04-22 19:29 UTC, merged